### ISSUE TITLE
RFE: Add more informative message for unresolved build dependencies (stone.yaml)

### ISSUE THREAD

**Issue by ermo** [GZGavinZhao/autobuild#12]
As I was experimenting with using `autobuild` to validate the current tree state of the serpent-os recipes tree, I saw a fair few cases of the following message:

`Package foo has unresolved build dependencies, graph may be incomplete!`

Is there any way to make this message more informative by showing the actual buildeps that couldn't be resolved?

For context, this is the bash invocation I used to parse the entire tree, recipe by recipe:
```
ermo@solbox:~/repos/serpent-os/recipes [autobuild-rebuilds* +1 ~0 -0 !]
for d in $(find -name stone.yaml | sed -e 's|stone\.yaml||');
do
  autobuild query src:. $(basename $d);
done
```
**Example:**
```
ermo@solbox:~/repos/serpent-os/recipes [autobuild-rebuilds* +3 ~0 -0 !]
$ autobuild query src:. valgrind
 ✗  Duplicate provider for libprintbackend-file.so(x86_64) from gtk-4, currently gtk-3
 🗸  Successfully parsed state!
 🗲  Package valgrind has unresolved build dependencies, build graph may be incomplete!
 🗸  Found all requested packages in state!
 🗸  Successfully built dependency graph!
 🗸  Build order: valgrind
```

**Comment by GZGavinZhao** [comment]
Yes, I'll work on this later today.

**Comment by ermo** [comment]
Fixed in https://github.com/GZGavinZhao/autobuild/commit/cf0440906667feb90f7a6b6d36a839093c03339c
