### ISSUE TITLE
Derpy cycles detection

### ISSUE THREAD

**Issue by GZGavinZhao** [GZGavinZhao/autobuild#2]
Putting notes here so I don't forget.

Repro:
```
autobuild query src:<path-to-packages> llvm llvm15
```

There's about a 50% chance it will say cyclic dependencies when there clearly shouldn't be any.

I found this problem all the way back in November or December yet I'm still unable to figure why the heck this happens.

**Comment by joebonrichie** [comment]
I wonder if this is due to `fastwalk`, as in the order the different threads walk the dir, or something funky going on with the mutex. Does swapping that out for bog standard filepath.WalkDir help?

**Comment by GZGavinZhao** [comment]
Fixed by 1fdcd94484ff3d7d16f6888af31fc821345e221b and 889a25ce4377c63c2128219cc2322584cacfd43f. Please comment if you find inconsistent output for two consecutive runs.
