### ISSUE TITLE
Initial flags for `autobuild query`

### ISSUE THREAD

**Issue by GZGavinZhao** [GZGavinZhao/autobuild#6]
- `--full`: every node that (transitively) depends on the given packages
- `--minimal` or `--onelevel`: one level incoming and one level outgoing for each package given
- `--only`: only consider the list of nodes given.
- `--level n`: same as `--onelevel`, but with configurable depth/level to search for?

This is not final and may be continuously changing.

**Comment by ermo** [comment]
I think I prefer `--onelevel` over `--minimal`.

`--all` might also shorten nicer than `--full` and be more "countable"?

**Comment by ermo** [comment]
A different way of thinking about it:

Might it also pay to be able to specify `--forward/--fwd/-F` and `--reverse/--rev/-R` and then using [0..n] integers as the level, with `a` meaning all and being the value that a too large `n` would truncate to?

Use case:

I update three packages which might be part of the same build graph and want to know what the fallout for those updates is, so I can choose whether to do a big PR or several smaller ones.

I start out by heading to the root of the solus packages git clone and doing a:

    autobuild query source:. --forward=1 pkg1 pkg2 pkg3
    (or)
    autobuild q src:. -F1 pkg pkg2 pkg3

followed by a:

    autobuild query source:. --reverse=1 pkg1 pkg2 pkg3
    (or)
    autobuild q src:. -R1 pkg pkg2 pkg3

At this point, I should have a decent idea of whether it's worth it for me to do the three packages in one run or not?

For a full resolution that takes into account all nodes in the tree, this might be a good way to do it:

    autobuild query source:. --forward=all pkg1 pkg2 pkg3
    (or)
    autobuild q src:. -Fa pkg1 pkg2 pkg2
    (reverse would be -Ra instead)

For a shallow resolution (just the ordering of the specified package list), this might do it:

    autobuild query source:. --forward=0 pkg1 pkg2 pkg3
    (or)
    autoubild q src:. -F0 pkg1 pkg2 pkg3
    (reverse would be -R0 instead)

**Comment by ermo** [comment]
Fixed in https://github.com/GZGavinZhao/autobuild/commit/c41630ce9ff6fe516f6e09be055b7ab01d0795d2

**Comment by ermo** [comment]
Fixed in https://github.com/GZGavinZhao/autobuild/commit/c41630ce9ff6fe516f6e09be055b7ab01d0795d2 (I don't have permissions that enable me to close this as fixed)
